services:
  db:
    image: mariadb:11
    container_name: calculator-db
    environment:
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_DATABASE: calc_data
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-proot123"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build: .

    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: